version: '3.7'

services:
    app_she:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: app_she
        ports:
            - "811:80"   # Akses via http://alamat-ip:811
            - "8453:443"  # Akses via https://alamat-ip:8453
        env_file:
            - backend/.env
        volumes:
            - ./backend/storage:/app/storage
            - caddy_data:/data
            - caddy_config:/config
        # Note: Untuk production, hindari mounting seluruh folder root (.) 
        # agar tidak menimpa file yang sudah di-build di dalam container.
        networks:
            - laporac_net

networks:
    laporac_net:
        driver: bridge

volumes:
    caddy_data:
    caddy_config:


