-- 1. Modify ASSETS table to track maintenance interval
ALTER TABLE public.assets
ADD COLUMN IF NOT EXISTS maintenance_interval_days INTEGER DEFAULT 90, -- Default Quarterly
ADD COLUMN IF NOT EXISTS last_maintenance_date DATE,
ADD COLUMN IF NOT EXISTS next_maintenance_date DATE;

-- 2. Create MAINTENANCE_SCHEDULES table (replacing work_orders concept)
CREATE TABLE IF NOT EXISTS public.maintenance_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT REFERENCES public.assets(id) ON DELETE CASCADE NOT NULL,
    
    scheduled_date DATE NOT NULL,
    completed_date DATE,
    
    status TEXT CHECK (status IN ('scheduled', 'in_progress', 'completed', 'missed', 'skipped')) DEFAULT 'scheduled',
    
    ticket_id BIGINT REFERENCES public.tickets(id) ON DELETE SET NULL, -- Link to generated Ticket (Work Order)
    technician_notes TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Enable RLS
ALTER TABLE public.maintenance_schedules ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies

-- Admins (GA) Manage Everything
CREATE POLICY "Admins can manage schedules"
ON public.maintenance_schedules
FOR ALL
USING (
  auth.uid() IN (
    SELECT id FROM public.profiles WHERE role IN ('super_admin', 'admin')
  )
);

-- Technicians View Only (Actual work is largely via Tickets)
CREATE POLICY "Technicians can view schedules"
ON public.maintenance_schedules
FOR SELECT
USING (
  auth.uid() IN (
    SELECT id FROM public.profiles WHERE role = 'technician'
  )
);

-- Dept Heads View Only
CREATE POLICY "Dept Heads can view schedules"
ON public.maintenance_schedules
FOR SELECT
USING (
  auth.uid() IN (
    SELECT id FROM public.profiles WHERE role = 'dept_head'
  )
);
