-- Migration: Asset Lifecycle Management
-- 1. Add Financial & Procurement Columns to 'assets'
ALTER TABLE assets
ADD COLUMN IF NOT EXISTS purchase_price DECIMAL(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS purchase_date DATE, -- Already exists in some versions, but ensuring it.
ADD COLUMN IF NOT EXISTS warranty_expiry_date DATE,
ADD COLUMN IF NOT EXISTS vendor_name TEXT,
ADD COLUMN IF NOT EXISTS useful_life_years INTEGER DEFAULT 5, -- For straight-line depreciation
ADD COLUMN IF NOT EXISTS residual_value DECIMAL(12, 2) DEFAULT 0, -- Scrap value
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

-- 2. Create 'asset_disposals' table for Write-off/Disposal tracking
CREATE TABLE IF NOT EXISTS asset_disposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT REFERENCES assets(id),
    disposal_date DATE NOT NULL DEFAULT CURRENT_DATE,
    disposal_type TEXT CHECK (disposal_type IN ('sold', 'scrapped', 'lost', 'donated')),
    sale_price DECIMAL(12, 2) DEFAULT 0,
    notes TEXT,
    authorized_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. RLS for Disposals (Admins only)
ALTER TABLE asset_disposals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage disposals"
ON asset_disposals FOR ALL
USING (is_admin());

CREATE POLICY "Technicians can view disposals"
ON asset_disposals FOR SELECT
USING (auth.uid() IN (SELECT id FROM profiles WHERE role IN ('admin', 'super_admin', 'technician')));
