-- Audit Trail Schema

-- 1. Create table
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    
    action TEXT NOT NULL, -- e.g., 'LOGIN', 'CREATE_ASSET', 'VERIFY_TICKET'
    target_table TEXT,    -- e.g., 'tickets', 'assets'
    target_id TEXT,       -- e.g., '101' (Stored as text to handle varying ID types)
    
    details JSONB DEFAULT '{}'::JSONB, -- Snapshot of changes or metadata
    
    ip_address TEXT,
    user_agent TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enable RLS
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- 3. Policies

-- Policy: Authenticated users can INSERT logs (System writes mostly, but client triggers it)
CREATE POLICY "Authenticated users can insert logs"
ON public.audit_logs
FOR INSERT
TO authenticated
WITH CHECK (true);

-- Policy: Only Admins can VIEW logs
CREATE POLICY "Admins can view audit logs"
ON public.audit_logs
FOR SELECT
USING (public.is_admin());

-- Policy: NO ONE can UPDATE or DELETE logs (Immutability)
-- (No policies created for UPDATE/DELETE means they are implicitly denied)
