-- Maintenance Work Orders Schema
-- 1. Create table
CREATE TABLE IF NOT EXISTS public.maintenance_work_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT REFERENCES public.assets(id) NOT NULL,
    technician_id UUID REFERENCES auth.users(id), -- Specific technician assigned
    
    scheduled_date DATE NOT NULL,
    completion_date TIMESTAMP WITH TIME ZONE,
    
    status TEXT CHECK (status IN ('scheduled', 'in_progress', 'completed', 'verified', 'missed')) DEFAULT 'scheduled',
    
    -- JSONB for flexible checklists. Example: {"filter_cleaned": true, "freon_pressure": "120psi"}
    checklist_data JSONB DEFAULT '{}'::JSONB, 
    
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enable RLS
ALTER TABLE public.maintenance_work_orders ENABLE ROW LEVEL SECURITY;

-- 3. Policies
CREATE POLICY "Admins can manage all work orders"
ON public.maintenance_work_orders
FOR ALL
USING (public.is_admin());

CREATE POLICY "Technicians can view assigned work orders"
ON public.maintenance_work_orders
FOR SELECT
USING (technician_id = auth.uid() OR public.is_admin());

CREATE POLICY "Technicians can update assigned work orders"
ON public.maintenance_work_orders
FOR UPDATE
USING (technician_id = auth.uid());
